MvcSchoolWebApp/Controllers/ESSController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using MvcSchoolWebApp.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using MvcSchoolWebApp.Controllers;

namespace MvcSchoolWebApp.Controllers
{
    public class ESSController : Controller
    {
        MessageCls msgobj = new MessageCls();
        public static string user_role;
        public static string user_id;
        public static string user_campus;
        public static string user_class;
        public static string user_section;
        public static string upd_attd_popup;
        public static string pagetype;
        DatabaeseClass db;
        DatabaseInsertClass din;
        public static List<Users> user_dtl;
        public static string updatedqry;
        string cs = ConfigurationManager.ConnectionStrings["Falconlocal"].ConnectionString;
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (HttpContext.Session["User_Dtl"] != null)
            {
                user_dtl = (List<Users>)HttpContext.Session["User_Dtl"];
                base.OnActionExecuting(filterContext);
                user_role = user_dtl[0].user_earea;
                user_id = user_dtl[0].user_id;
            }
            else
            {
                filterContext.Result = new RedirectResult("~/Login");
            }
        }
        public ActionResult payslip()
        {
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();

            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            if (list[44].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");
            }

            DatabaeseClass dc = new DatabaeseClass();
            ESSModel ess = new ESSModel();
            
            SqlConnection conn = new SqlConnection(cs);
            conn.Open();
            string query = "select Top 1 earea from empmain where empid = '" + user_id + "' and delind <> 'X' order by recordno desc";
            SqlCommand cmd = new SqlCommand(query, conn);
            ess.society = cmd.ExecuteScalar().ToString();

            conn.Close();
            DateTime lastmonth = dc.convertservertousertimezone(DateTime.Now.ToString());
            DateTime firstday = lastmonth.AddDays(1 - DateTime.Now.Day).AddMonths(-1);
            DateTime lastday = new DateTime(firstday.Year, firstday.Month, DateTime.DaysInMonth(firstday.Year, firstday.Month));

            ess.empid = user_id;
            
            ess.begdate = firstday.ToString("dd-MMMM-yyyy");
            ess.enddate = lastday.ToString("dd-MMMM-yyyy");
            return View(ess);
        }

        [HttpPost]
        public ActionResult payslip(ESSModel ess)
        {
            SqlConnection conn = new SqlConnection(cs);
            conn.Open();
            string earea = "select distinct earea from empmain where empid = '" + user_id + "' and delind <> 'X'";
            SqlCommand cmd = new SqlCommand(earea, conn);
            string rptid = "ZHR001";
            ReportsController rc = new ReportsController();
            string[] arr = new string[7];
            arr[0] = ess.empid;
            arr[1] = ess.empid;
            arr[2] = Convert.ToDateTime(ess.begdate).ToString("yyyy-MM-dd");
            arr[3] = Convert.ToDateTime(ess.enddate).ToString("yyyy-MM-dd");
            arr[4] = "";
            arr[5] = cmd.ExecuteScalar().ToString();
            arr[6] = "";

            string[] formula_values = new string[2];
            formula_values[0] = Convert.ToDateTime(ess.begdate).ToString("dd/MM/yyyy");
            formula_values[1] = Convert.ToDateTime(ess.enddate).ToString("dd/MM/yyyy");

            string updatedquery = rc.getupdatedquery(rc.getsquery(rptid), arr);
            System.IO.Stream stream = rc.getrptstream(rptid, updatedquery, formula_values);
            return File(stream, "application/pdf");
        }

        public ActionResult leaveRequest()
        {          
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();

            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            if (list[45].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");
            }

            db = new DatabaeseClass();
            List<ESSModel> track_loan = db.track_leave_status(user_id);
            if (track_loan != null)
            {
                ViewBag.trackinglist = track_loan;
            }

            ESSModel model = new ESSModel();
            db = new DatabaeseClass();
            List<ESSModel> dblist = db.getemploydetail(user_id);
            ViewBag.empid = dblist[0].empid;
            ViewBag.design = dblist[0].design;
            pagetype = "0210";
            model.loantyp = db.getLoanType(pagetype);
            ViewBag.date = db.converteddisplaydate(DateTime.Now.ToString()).ToString("dd-MMMM-yyyy");

            DatabaeseClass dc = new DatabaeseClass();
            DateTime currentday = dc.converteddisplaydate(DateTime.Now.ToString());
            ViewBag.date = currentday.ToString("dd-MMMM-yyyy");
            return View(model);
        }
        [HttpPost]
        public ActionResult leaveRequest(ESSModel model)
        {
            din = new DatabaseInsertClass();
            string msg = din.ESSLeaveInsert(model, user_id);

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();

            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            if (list[45].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");
            }
            model = new ESSModel();
            db = new DatabaeseClass();
            List<ESSModel> dblist = db.getemploydetail(user_id);
            ViewBag.empid = dblist[0].empid;
            ViewBag.design = dblist[0].design;
            pagetype = "0210";
            model.loantyp = db.getLoanType(pagetype);
            ViewBag.date = db.converteddisplaydate(DateTime.Now.ToString()).ToString("dd-MMMM-yyyy");

            DatabaeseClass dc = new DatabaeseClass();
            DateTime currentday = dc.converteddisplaydate(DateTime.Now.ToString());
            ViewBag.date = currentday.ToString("dd-MMMM-yyyy");
            if (msg == "Success")
            {
                ViewBag.Message = msg;
            }
            else
            {
                ViewBag.Message = msg;
            }
            return View(model);
        }

        public ActionResult loanRequest()
        {
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();

            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            if (list[46].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");
            }

            db = new DatabaeseClass();
            List<ESSModel> track_loan = db.track_loan_status(user_id);
            if (track_loan != null)
            {
                ViewBag.trackinglist = track_loan;
            }

            ESSModel model = new ESSModel();
            db = new DatabaeseClass();
            List<ESSModel> dblist = db.getemploydetail(user_id);
            DateTime dt = Convert.ToDateTime(dblist[0].joindate);
            DateTime dt2 = Convert.ToDateTime(dblist[0].confrdate);
            ViewBag.empid = dblist[0].empid;
            ViewBag.joindate = dt.ToString("dd-MMMM-yyyy");
            ViewBag.confrdate = dt2.ToString("dd-MMMM-yyyy");
            ViewBag.design = dblist[0].design;
            ViewBag.dept = dblist[0].dept;
            pagetype = "0360";
            model.loantyp = db.getLoanType(pagetype);
            ViewBag.date = db.converteddisplaydate(DateTime.Now.ToString()).ToString("dd-MMMM-yyyy");
            return View(model);
       }

        [HttpPost]
        public ActionResult loanRequest(ESSModel model)
        {
            din = new DatabaseInsertClass();
            string msg = din.ESSLoanInsert(model,user_id);
            
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();

            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            if (list[46].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");
            }
            db = new DatabaeseClass();
            List<ESSModel> dblist = db.getemploydetail(user_id);
            DateTime dt = Convert.ToDateTime(dblist[0].joindate);
            DateTime dt2 = Convert.ToDateTime(dblist[0].confrdate);
            ViewBag.empid = dblist[0].empid;
            ViewBag.joindate = dt.ToString("dd-MMMM-yyyy");
            ViewBag.confrdate = dt2.ToString("dd-MMMM-yyyy");
            ViewBag.design = dblist[0].design;
            ViewBag.dept = dblist[0].dept;
            pagetype = "0360";
            model.loantyp = db.getLoanType(pagetype);
            ViewBag.date = db.converteddisplaydate(DateTime.Now.ToString()).ToString("dd-MMMM-yyyy");

            if (msg == "Success")
            {
                ViewBag.Message = msg;
            }
            else
            {
                ViewBag.Message = msg;
            }
            return View(model);
        }

        public ActionResult resignRequest()
        {
            ViewBag.msglist = msgobj.GetNotifications();

MvcSchoolWebApp/Views/ESS/leaveRequest.cshtml
@model MvcSchoolWebApp.Models.ESSModel
@{
    ViewBag.Title = "Index";
}

<section class="content">
    <!-- Info boxes -->
@using (Html.BeginForm("leaveRequest", "ESS", FormMethod.Post))
{
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div id="dvborder">
                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Employee Self Service
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    Leave Request
                                </label>
                            </li>
                        </ul>
                    </div>

                    <div class="ibox-content">
                        <div class="row">
                            <div class="row ">
                                <div class="col-md-12">
                                    <div class="col-md-2">
                                        <label>Employee Id</label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(model => model.empid, "Employee Code", new { @Value = ViewBag.empid, @class = "form-control m-b", @name = "txtempidLvR", @id = "txtempidLvR", @readonly = true })
                                    </div>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-md-12">
                                    <div class="col-md-2">
                                        <label>Designation</label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(model => model.design, "Designation", new { @Value = ViewBag.design, @class = "form-control m-b", @name = "txtdesigLvR", @id = "txtdesigLvR", @required = true, @readonly = true })
                                    </div>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-md-12">

                                    <div class="col-md-2">
                                        <label>Type of Leave(s)</label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(m => m.loanid, Model.loantyp, "Leave type", new { @class = "form-control m-b", @name = "txtLeavetypLvR", @id = "txtLeavetypLvR", @required = true })
                                    </div>

                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label>First Day of Leave</label>
                                    </div>
                                    <div class="col-md-7" style="margin-left:5px;">
                                        @Html.TextBoxFor(model => model.begdate, "Date", new { @Value = ViewBag.date, @class = "form-control m-b", @name = "txtbegdateLvR", @id = "txtbegdateLvR", @required = true})
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label>Last Day of Leave</label>
                                    </div>
                                    <div class="col-md-7">
                                        @Html.TextBoxFor(model => model.lastdate, "Date", new { @Value = ViewBag.lastdate, @class = "form-control m-b", @name = "txtlastdateLvR", @id = "txtlastdateLvR", @required = true})
                                        @* @Html.TextBoxFor(model => model.teachername, new { @class = "form-control m-b", @name = "txtTeacherMU", @id = "txtTeacherMU", @readonly = true, @required = true })*@
                                    </div>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-md-12">
                                    <div class="col-md-2">
                                        <label>Total number of days</label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(model => model.totdays, new { @Value = "0", @class = "form-control m-b", @name = "txtnumDayLvR", @id = "txtnumDayLvR", @required = true, @readonly = true })
                                    </div>
                                </div>
                            </div>

                            <div class="row ">
                                <div class="col-md-12">
                                    <div class="col-md-2">
                                        <label>Comments</label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextAreaFor(model => model.reason, new { @class = "form-control m-b", @name = "txtReasonLvR", @id = "txtReasonLvR", @required = true, @style = "resize:vertical; height:100px;" })

                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="col-md-5 form-group">
                                        <input type="submit" value="Submit" name="btnEnter" class="btn btn-sm btn-danger" />
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <span style="color:green">@ViewBag.Message</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div id="dvborder">
                    <div class="ibox-title ">
                        <h3>
                            Leave Status
                        </h3>
                    </div>

                    <div class="ibox-content">
                        <form id="attendanceForm" role="form" name="attendanceForm">
                            <div class="row">
                                <div class="col-md-3"><label>Approver</label></div>
                                <div class="col-md-3"><label>Accepted</label></div>
                                <div class="col-md-3"><label>Rejected</label></div>
                                <div class="col-md-3"><label>Comments</label></div>
                            </div>

                            @{
                                var items = ViewBag.trackinglist;
                                bool accepted = false;
                                if (items != null)
                                {
                                    int i = 0;
                                    foreach (var list in items)
                                    {
                                        i++;
                                        <div class="row">
                                            <div class="col-md-3"> <label> @list.appvrid </label> </div>
                                            @if (list.loan_status == "01" || list.loan_status == "02")
                                            {
                                                <div class="col-md-3"><label><input type="radio" name="@i" value="CEO" style="display:inline" checked disabled></label></div>
                                                <div class="col-md-3"><label><input type="radio" name="@i" value="CEO" style="display:inline" disabled></label></div>
                                            }
                                            else if (list.loan_status == "04" || list.loan_status == "05")
                                            {
                                                <div class="col-md-3"><label><input type="radio" name="@i" value="CEO" style="display:inline"></label></div>
                                                <div class="col-md-3"><label><input type="radio" name="@i" value="CEO" style="display:inline"></label></div>
                                            }
                                            else
                                            {
                                                <div class="col-md-3"><label><input type="radio" name="@i" value="CEO" style="display:inline"></label></div>
                                                <div class="col-md-3"><label><input type="radio" name="@i" value="CEO" style="display:inline" checked></label></div>
                                            }
                                            <div class="col-md-3"> <textarea class="form-control m-b" style="resize:none;" disabled> @list.comments </textarea> </div>
                                        </div>
                                    }
                                }

                            }
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MvcSchoolWebApp/Views/ESS/payslip.cshtml
@model MvcSchoolWebApp.Models.ESSModel
@{
    ViewBag.Title = "payslip";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="content">
    <div class="row">

        <div class="col-lg-12">

            <div class="ibox float-e-margins">
                <div id="dvborder">

                    <div class="ibox-title ">

                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Employee Self Service
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    Employee Pay Slip
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            @using (Html.BeginForm("payslip", "ESS", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                <form id="frm_payslip">
                                    <div class="row ">

                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Employee Id</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.TextBoxFor(model => model.empid, new { @type = "text", @class = "form-control m-b", @name = "txtempidPS", @id = "txtempidPS", @placeholder = "Employee Id", @requried = "true", @readonly = "true" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row ">
                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>From Date</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.TextBoxFor(model => model.begdate, new { @type = "text", @class = "date-day form-control m-b", @name = "txtbegdatePS", @id = "txtbegdatePS", @requried = "true"})
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>To Date</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.TextBoxFor(model => model.enddate, new { @type = "text", @class = "date-day form-control m-b", @name = "txtenddatePS", @id = "txtenddatePS", @requried = "true" })
                                            </div>
                                        </div>

                                    </div>
                                    @*<div class="row ">

                                            <div class="col-md-4">
                                                <div class="col-md-5">
                                                    <label>esubarea</label>
                                                </div>
                                                <div class="col-md-7">
                                                    <input type="text" placeholder="esubarea" class="form-control m-b" name="txtesubareaPS" id="txtesubareaPS" />
                                                </div>
                                            </div>
                                        </div>*@
                                    <div class="row ">

                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Society</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.TextBoxFor(model => model.society, new { @type = "text", @class = "form-control m-b", @name = "txteareaPS", @id = "txteareaPS", @requried = "true", @disabled = "true" })
                                            </div>
                                        </div>
                                    </div>
                                    @*<div class="row ">

                                            <div class="col-md-4">
                                                <div class="col-md-5">
                                                    <label>eesubgrp</label>
                                                </div>
                                                <div class="col-md-7">
                                                    <input type="text" placeholder="eesubgrp" class="form-control m-b" name="txteesubgrpPS" id="txteesubgrpPS" />
                                                </div>
                                            </div>
                                        </div>*@
                                    <div class="row ">
                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <input id="btnformPS" type="submit" value="Submit" name="btnEnter" class="btn btn-sm btn-danger" />
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            }
                            
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
<script src=@Url.Content("~/Content/dbtheme/plugins/jQuery/jquery-2.2.3.min.js?n=1")></script>
<script>
    
    @*$("#frm_payslip").submit(function (e) {
    debugger
    e.preventDefault();
    var param = new Array();
    param[0] = $("#txtbegdatePS").val();
    param[1] = $("#txtenddatePS").val();
    param[2] = $("#txtesubareaPS").val();
    param[3] = $("#txteesubgrpPS").val();
    var paramvalues = param[0] + ',' + param[1] + ',' + param[2] + ',' + param[3];
    window.location.href = '@Url.Action("getsquery", "ESS") ' + '?param=' + paramvalues;*@

    //$.post("/ESS/getsquery", $.param(param, true));
    //$.ajax({
    //    type: "POST",
    //    url: encodeURI("../ESS/getsquery"),
    //    data: {
    //        param: param
    //    },
    //    success: function (data) {
    //        show_alert_js('Success');
    //    },
    //    error: function (data) {
    //        show_err_alert_js('Found Some Error! Please Try Again');
    //    },
    //    dataType: "json"
    //});
//});
</script>


<script src=@Url.Content("~/Content/js/PaySlip.js?n=1")></script>